spring:
  application:
    name: kafka-topic
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
      minimumIdle: 5
      auto-commit: true
      registerMbeans: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        #format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080